---
- name: Cau hinh tren router
  hosts: Router
  gather_facts: no

  tasks:
    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: output

    - debug: var=output.stdout

    - name: parse output
      command_parser:
        file: "parsers/ios/show_ip_interface_brief.yaml"
