---
- name: Cau hinh tren router
  hosts: 10.215.11.68

  tasks:
    - name: Dat ip cho cong fastEthernet0/1
      ios_l3_interface:
        name: fastEthernet0/1
        ipv4: 192.168.1.1/24

    - name: dat ip subinterface
      ios_config:
        lines:
          -encapsulation dot1Q {{item.vlan}}
          -ip address 192.168.{{item.vlan}}.1 255.255.255.0
        parents: {{item.subint}}
      with_items:
        - { subint: fastEthernet0/1.10 , vlan: 10 }
        - { subint: fastEthernet0/1.20 , vlan: 20 }
        - { subint: fastEthernet0/1.30 , vlan: 30 }

    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: show_ip

    - debug: var=show_ip.stdout_lines

---
- name: Cau hinh tren Switch
  hosts: 10.215.11.66

  tasks:
    - name: tao vlan
      ios_config:
        lines:
          -vlan {{item}}
          -exit
      with_items:
        - 10
        - 20
        - 30

    - name: gan cong vao vlan
      ios_config:
        lines:
          - switchport mode access
          - switch access vlan {{item.vlan}}
          - exit
        parents: {{item.int}}
      with_items:
        - { vlan: 10, int: fastEthernet0/1}
        - { vlan: 20, int: fastEthernet0/2}
        - { vlan: 30, int: fastEthernet0/3}

    - name: trunking tren switch
      ios_config:
        lines:
          - switchport trunk encapsulation dot1Q
          - switchport mode trunk
      parents: fastEthernet0/0
