---
- name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
    - name: Create vlan
      ios_vlan:
        vlan_id: "{{ item }}"
        name: "{{ item }}"
        state: present
      loop:
        - 11
        - 12
        - 13
        - 14
        - 15
